Add support for changing release channel of all apps
GrapheneOS/Apps pull request #205
Opened 2022-09-09 08:36 UTC by octocorvus

This resolves #137 by doing two things:
1. Adds setting for changing the default channel for all apps, in the main settings screen.
2. Adds support for resetting the channel in per-app release channel settings.

No regressions in initial testing. I need some help testing it, since I can't confirm if changing channel with the new settings works and user gets the appropriate channel. Although, it should logically as per the code.

2022-09-09 11:15 UTC, empratyush requested changes

2022-09-09 14:13 UTC, empratyush commented on app/src/main/java/org/grapheneos/apps/client/ui/settings/MainSettings.kt
> +import androidx.preference.Preference
both approach is fine, mostly it good to keep things separate Settings ui should not be changed stuff directly (that will make replacing it with compose or something else very easy).
you don't have to call unregister if you are using application context to register it.

2022-09-09 14:21 UTC, empratyush commented on app/src/main/java/org/grapheneos/apps/client/ui/detailsScreen/DetailsScreen.kt
> -                        packageInfo.selectedVariant.type
`packageInfo.selectedVariant.type` value should be same isn't it?

2022-09-09 16:03 UTC, octocorvus commented
I refactored the code, modified variables and added some comments to prevent confusion.

2022-09-29 08:34 UTC, octocorvus commented
Rebased changes

2022-12-25 13:51 UTC, octocorvus commented
Needs to be redone after rewrite

2022-12-25 13:51 UTC, closed without merging